select * from customers limit 10

-- Q1. What is the total revenue generated by Male VS. Female customers? 
SELECT gender, SUM(purchase_amount) AS revenue
FROM customers 
GROUP BY gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount
FROM customers
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT  AVG(purchase_amount) FROM customers)

-- Q3. Which are the top 5 products with the highest average review rating? 
SELECT item_purchased AS product, ROUND(AVG(review_rating::numeric),2) AS "Average product rating"
FROM customers
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4. Compare the average purchases amount between standard and express shipping. 
SELECT shipping_type, ROUND(AVG(purchase_amount),2)
FROM customers 
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type

-- Q5. Do subscribed customers spend more? compare average spend and total revenue between subscriber and non-subsriber.
SELECT subscription_status,COUNT(customer_id) AS total_customers ,
       ROUND(AVG(purchase_amount),2) AS avg_spend,  ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customers
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchase with discount applied? 
SELECT item_purchased,
       ROUND(100.0*SUM(CASE WHEN discount_applied ='Yes' THEN 1 ELSE 0 END )/COUNT(*),2) AS discount_rate
 FROM customers 
 GROUP BY item_purchased
 ORDER BY discount_rate DESC
 LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
WITH customer_type AS(
 SELECT customer_id, previous_purchases,
 CASE 
      WHEN previous_purchases = 1 THEN 'New'
      WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
      ELSE 'Loyal' END AS customer_segment
FROM customers
)
SELECT customer_segment, COUNT(*) AS "Number of customers"
FROM customer_type
GROUP BY customer_segment;
 
-- Q8. What are the most 3 purchased products within each cateogry? 
WITH item_count AS(
SELECT category, 
item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customers
GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_count
WHERE item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe? 
SELECT subscription_status, 
       COUNT(customer_id) AS repeat_buyers
FROM customers 
WHERE previous_purchases > 5 
GROUP BY subscription_status;

-- Q10. What is the revenue contribution to each age group? 
SELECT age_group,
       SUM(purchase_amount) AS Revenue,
       COUNT(customer_id) AS "No. buyers"
FROM customers 
GROUP BY age_group
ORDER BY Revenue DESC;





